### ISSUE TITLE
Error Setting up Entry

### ISSUE THREAD

**Issue by danielcaldentey** [pcartwright81/Home-Assistant-Here-Comes-The-Bus#49]
### System Health details

HA Core: 2024.11.2
HA Supervisor: 2024.11.2
HA OS: 13.2
Frontend: 20241106.2

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/pcartwright81/Home-Assistant-Here-Comes-The-Bus/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I setup the entry with my username (email), password, and school code, but I can't get the instance to load. Am I doing something wrong?

### Reproduction steps

1. Add Instance
2. Fill in username, password and school number

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 2:41:01 PM (3 occurrences)
Last logged: 4:05:56 PM

Error setting up entry Here Comes The Bus for here_comes_the_bus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/here_comes_the_bus/__init__.py", line 51, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/config/custom_components/here_comes_the_bus/coordinator.py", line 69, in async_config_entry_first_refresh
    await self.config_entry.runtime_data.client.get_stop_info(
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/hcb_soap_client.py", line 126, in get_stop_info
    return StopResponse.from_text(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/stop_response.py", line 172, in from_text
    stops = from_list(StudentStop.from_dict, student_stops)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/__init__.py", line 45, in from_list
    return [f(y) for y in x]
            ^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/stop_response.py", line 54, in from_dict
    bus_visibility_start_offset = from_int(
                                  ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/__init__.py", line 34, in from_int
    return int(from_str(x))
           ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by pcartwright81** [comment]
The code passed the first two calls but failed on the third. I'm going to add some error handling and logging to the build, specifically to prevent that blank field from causing issues.

**Comment by danielcaldentey** [comment]
> The code passed the first two calls but failed on the third. I'm going to add some error handling and logging to the build, specifically to prevent that blank field from causing issues.

Thank you!

**Comment by pcartwright81** [comment]
The fix for that error is pushed.  Try version 0.0.11.  All sensors except for arrival time will be blank unless it is within the actual bus movement times.

**Comment by danielcaldentey** [comment]
I'm unfortunately still having the same problem, and the log seems to be identical. I double-checked the version and it does show 0.0.11, so I'm not sure what's wrong
![image](https://github.com/user-attachments/assets/87277880-a32a-402e-afb3-837b2ff6e816)

Here's the log:
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 7:29:00 PM (1 occurrences)
Last logged: 7:29:00 PM

Error setting up entry Here Comes The Bus for here_comes_the_bus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/here_comes_the_bus/__init__.py", line 51, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/config/custom_components/here_comes_the_bus/coordinator.py", line 69, in async_config_entry_first_refresh
    await self.config_entry.runtime_data.client.get_stop_info(
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/hcb_soap_client.py", line 126, in get_stop_info
    return StopResponse.from_text(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/stop_response.py", line 172, in from_text
    stops = from_list(StudentStop.from_dict, student_stops)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/__init__.py", line 45, in from_list
    return [f(y) for y in x]
            ^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/stop_response.py", line 54, in from_dict
    bus_visibility_start_offset = from_int(
                                  ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hcb_soap_client/__init__.py", line 34, in from_int
    return int(from_str(x))
           ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by pcartwright81** [comment]
Sorry forgot to update a file.  v0.1.2 is up.

Fixed the version here too.
<img width="159" alt="image" src="https://github.com/user-attachments/assets/8ed1070a-9f97-4dc7-b69f-578cd4e713a7">

**Comment by danielcaldentey** [comment]
Now it works perfectly, thank you very much!

**Comment by danielcaldentey** [comment]
Thanks for all your help!
